### ISSUE TITLE
Receptive Field Region

### ISSUE THREAD

**Issue by hamedbehzadi** [Fangyh09/pytorch-receptive-field#13]
Hi
Thanks for sharing this code as I don't see another library in pytorch for this.
Does the code compute the receptive field region for any feature location in a feature map?or just compute the size of the field for each layer?

Thank you

**Comment by Fangyh09** [comment]
> Does the code compute the receptive field region for any feature location in a feature map?

Yes, this can be inferred from output.

**Comment by Fangyh09** [comment]
Function receptive_field_for_unit https://github.com/Fangyh09/pytorch-receptive-field/blob/master/main.py#L28
