### ISSUE TITLE
works for 1d conv?

### ISSUE THREAD

**Issue by listener17** [Fangyh09/pytorch-receptive-field#15]
Hello! Lets say, I have 1d convolutional network (with also some 1d transposed convolution) - can this code be used to compute the receptive field of the whole model?

**Comment by Fangyh09** [comment]
It can be extended to 1d convolutional network.

I feel just adding 1d convolutional network operators to [here](https://github.com/Fangyh09/pytorch-receptive-field/blob/master/torch_receptive_field/receptive_field.py#L45) might work. 


Similar pr: https://github.com/Fangyh09/pytorch-receptive-field/pull/11/files.

**Comment by listener17** [comment]
Works! Thanks!

**Comment by chiyuzhang94** [comment]
> Works! Thanks!

Hi @listener17 @Fangyh09 , could you share the code for analyzing 1D CNN?

Thanks.
