### ISSUE TITLE
start computing

### ISSUE THREAD

**Issue by xyukiono** [Fangyh09/pytorch-receptive-field#3]
Hi, Thank you for sharing codes.  

I noticed that computing for **start** might be wrong. 

In your code, int wrapping are added but I think you don't have to because start is floating value.

- original code
``` 
receptive_field[m_key]["start"] = p_start + (int((kernel_size - 1) / 2) - padding) * p_j
```

- correct code?
```
receptive_field[m_key]["start"] = p_start + ((kernel_size - 1) / 2 - padding) * p_j
```

I think start value of layer4 is 1.0 in your example.

**Comment by Fangyh09** [comment]
Yes, you are right. Thanks!
