### ISSUE TITLE
dilation convolution receptive field

### ISSUE THREAD

**Issue by JayYangSS** [Fangyh09/pytorch-receptive-field#6]
It seems that your code can not handle the dilation convolution's receptive field.

**Comment by Fangyh09** [comment]
Currently, yes.

**Comment by khirotaka** [comment]
You should be able to deal with dilation if you do the following. (Maybe this problem has been solved...)

https://github.com/Fangyh09/pytorch-receptive-field/blob/5fee7d0e453df0ff4819c9b939c35a1e113133af/torch_receptive_field/receptive_field.py#L46-L53



```python
if class_name == "Conv2d" or class_name == "MaxPool2d":
    kernel_size = module.kernel_size
    stride = module.stride
    padding = module.padding
    dilation = module.dilation    # <- add
    kernel_size, stride, padding, dilation = map(
        check_same, [kernel_size, stride, padding, dilation]    # <- update
    )
    receptive_field[m_key]["j"] = p_j * stride
    receptive_field[m_key]["r"] = (
        p_r + ((kernel_size - 1) * dilation) * p_j    # <- update
    )
    receptive_field[m_key]["start"] = (
        p_start + ((kernel_size - 1) / 2 - padding) * p_j
    )
```

**Comment by ZhengdiYu** [comment]
> You should be able to deal with dilation if you do the following. (Maybe this problem has been solved...)
> 
> https://github.com/Fangyh09/pytorch-receptive-field/blob/5fee7d0e453df0ff4819c9b939c35a1e113133af/torch_receptive_field/receptive_field.py#L46-L53
> 
> ```python
> if class_name == "Conv2d" or class_name == "MaxPool2d":
>     kernel_size = module.kernel_size
>     stride = module.stride
>     padding = module.padding
>     dilation = module.dilation    # <- add
>     kernel_size, stride, padding, dilation = map(
>         check_same, [kernel_size, stride, padding, dilation]    # <- update
>     )
>     receptive_field[m_key]["j"] = p_j * stride
>     receptive_field[m_key]["r"] = (
>         p_r + ((kernel_size - 1) * dilation) * p_j    # <- update
>     )
>     receptive_field[m_key]["start"] = (
>         p_start + ((kernel_size - 1) / 2 - padding) * p_j
>     )
> ```

As for the code below:
    receptive_field[m_key]["start"] = (
        p_start + ((kernel_size - 1) / 2 - padding) * p_j
    )

Did you miss  * dilation ?

**Comment by Fangyh09** [comment]
The start is not affected. See https://github.com/vdumoulin/conv_arithmetic.

This pull is merged.
